### ISSUE TITLE
Does not longer deploy on latest buildpacks ootb old npm packages?

### ISSUE THREAD

**Issue by rmey** [IBM-Cloud/insurance-bot-dashboard#58]
Staging...
   -----> IBM SDK for Node.js Buildpack v3.20-20180403-1426
          Based on Cloud Foundry Node.js Buildpack v1.5.24
   -----> Creating runtime environment
          
          NPM_CONFIG_PRODUCTION=true
          NODE_MODULES_CACHE=true
          NPM_CONFIG_LOGLEVEL=error
   -----> Installing binaries
          NODE_ENV=production
          Downloading and installing node 6.7.0...
          engines.npm (package.json):   ^3.0.0
          engines.node (package.json):  6.7.0
          
          Resolving npm version ^3.0.0 via semver.io...
          Downloading and installing npm 3.10.10 (replacing version 3.10.3)...
   -----> Restoring cache
          Skipping cache restore (new runtime signature)
   -----> Checking and configuring service extensions before installing dependencies
          Installing node modules (package.json)
   -----> Building dependencies
          npm ERR! node v6.7.0
          npm ERR! code EREADFILE
          npm ERR! argv "/tmp/app/vendor/node/bin/node" "/tmp/app/vendor/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/app/.npmrc"
          npm ERR! Linux 4.4.0-109-generic
          
          npm ERR! npm  v3.10.10
          npm ERR! Error extracting /home/vcap/.npm/cloudant/1.9.0/package.tgz archive: ENOENT: no such file or directory, open '/home/vcap/.npm/cloudant/1.9.0/package.tgz'
          npm ERR!
          npm ERR! If you need help, you may report this error at:
          npm ERR!     <https://github.com/npm/npm/issues>
          npm ERR!     /tmp/app/npm-debug.log
          
          npm ERR! Please include the following file with any support request:
   -----> Build failed
          
   Failed to compile droplet: Failed to compile droplet: exit status 1
          
   Exit status 223
   Staging failed: STG: Exited with status 223
   Stopping instance 92202581-8e1d-4c03-8495-f19d0934a3f6
   Destroying container
   Successfully destroyed container

**Comment by l2fprod** [comment]
fixed with latest toolchain

**Comment by johnwen84** [comment]
@l2fprod hello, I'm starting to get the same error recently. Can you tell me what I need to do to get around it?
Thanks

**Comment by l2fprod** [comment]
@johnwen84

are you getting this with the insurance demo?
did you use the toolchain to deploy?
can you open an issue and share the log?
