### ISSUE TITLE
Cloudant Issue with npm -- see stackoverflow thread

### ISSUE THREAD

**Issue by rmey** [IBM-Cloud/insurance-bot-dashboard#60]
Cloudant npm faces the same issue described here:
[https://stackoverflow.com/questions/48848643/error-while-deploying-nodejs-app-on-ibm-bluemix](url)
`2018-04-25T19:36:35.98+0000 [STG/0] OUT        npm ERR! Error extracting /home/vcap/.npm/cloudant/1.9.0/package.tgz archive: ENOENT: no such file or directory, open '/home/vcap/.npm/cloudant/1.9.0/package.tgz'
   2018-04-25T19:36:35.98+0000 [STG/0] OUT        npm ERR!
   2018-04-25T19:36:35.98+0000 [STG/0] OUT        npm ERR! If you need help, you may report this error at:
   2018-04-25T19:36:35.98+0000 [STG/0] OUT        npm ERR!     <https://github.com/npm/npm/issues>
   2018-04-25T19:36:36.02+0000 [STG/0] OUT        
   2018-04-25T19:36:36.02+0000 [STG/0] OUT        npm ERR! Please include the following file with any support request:
   2018-04-25T19:36:36.02+0000 [STG/0] OUT        npm ERR!     /tmp/app/npm-debug.log
   2018-04-25T19:36:36.05+0000 [STG/0] OUT -----> Build failed`

**Comment by rmey** [comment]
[https://developer.ibm.com/answers/questions/443159/cf-push-for-watsons-food-agent-app-is-not-working/](url)
I had to change npm version in package.json
`"engines": {
    "node": "6.7.0",
    "npm": "5.6.0"
  },`

**Comment by l2fprod** [comment]
main issue coming from cloudant now using a "scoped" package (`@cloudant/cloudant`). The BUILD job fails, and then the DEPLOY

```
-----> Building dependencies
       npm ERR! Linux 4.4.0-109-generic
       npm ERR! argv "/tmp/app/vendor/node/bin/node" "/tmp/app/vendor/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/app/.npmrc"
       npm ERR! node v6.7.0
       npm ERR! npm  v3.10.10
       npm ERR! code EREADFILE
       
       npm ERR! Error extracting /home/vcap/.npm/cloudant/1.9.0/package.tgz archive: ENOENT: no such file or directory, open '/home/vcap/.npm/cloudant/1.9.0/package.tgz'
       npm ERR!
       npm ERR! If you need help, you may report this error at:
       npm ERR!     <https://github.com/npm/npm/issues>
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/app/npm-debug.log
-----> Build failed
       
       
Failed to compile droplet: Failed to compile droplet: exit status 1
```

**Comment by NafisFaisalKhan** [comment]
Was this solved?
I am getting this for firebase deploy.

**Comment by l2fprod** [comment]
the cloudant issue is solved. I don't understand the reference to "firebase"
